/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsPandudesaRouteImport } from './routes/projects.pandudesa'
import { Route as ProjectsKafeyaRouteImport } from './routes/projects.kafeya'
import { Route as ProjectsCuppingnotesRouteImport } from './routes/projects.cuppingnotes'
import { Route as ProjectsBeanhubRouteImport } from './routes/projects.beanhub'

const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsPandudesaRoute = ProjectsPandudesaRouteImport.update({
  id: '/projects/pandudesa',
  path: '/projects/pandudesa',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsKafeyaRoute = ProjectsKafeyaRouteImport.update({
  id: '/projects/kafeya',
  path: '/projects/kafeya',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsCuppingnotesRoute = ProjectsCuppingnotesRouteImport.update({
  id: '/projects/cuppingnotes',
  path: '/projects/cuppingnotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsBeanhubRoute = ProjectsBeanhubRouteImport.update({
  id: '/projects/beanhub',
  path: '/projects/beanhub',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/impact': typeof ImpactRoute
  '/journey': typeof JourneyRoute
  '/projects/beanhub': typeof ProjectsBeanhubRoute
  '/projects/cuppingnotes': typeof ProjectsCuppingnotesRoute
  '/projects/kafeya': typeof ProjectsKafeyaRoute
  '/projects/pandudesa': typeof ProjectsPandudesaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/impact': typeof ImpactRoute
  '/journey': typeof JourneyRoute
  '/projects/beanhub': typeof ProjectsBeanhubRoute
  '/projects/cuppingnotes': typeof ProjectsCuppingnotesRoute
  '/projects/kafeya': typeof ProjectsKafeyaRoute
  '/projects/pandudesa': typeof ProjectsPandudesaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/impact': typeof ImpactRoute
  '/journey': typeof JourneyRoute
  '/projects/beanhub': typeof ProjectsBeanhubRoute
  '/projects/cuppingnotes': typeof ProjectsCuppingnotesRoute
  '/projects/kafeya': typeof ProjectsKafeyaRoute
  '/projects/pandudesa': typeof ProjectsPandudesaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/experience'
    | '/impact'
    | '/journey'
    | '/projects/beanhub'
    | '/projects/cuppingnotes'
    | '/projects/kafeya'
    | '/projects/pandudesa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/experience'
    | '/impact'
    | '/journey'
    | '/projects/beanhub'
    | '/projects/cuppingnotes'
    | '/projects/kafeya'
    | '/projects/pandudesa'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/experience'
    | '/impact'
    | '/journey'
    | '/projects/beanhub'
    | '/projects/cuppingnotes'
    | '/projects/kafeya'
    | '/projects/pandudesa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ExperienceRoute: typeof ExperienceRoute
  ImpactRoute: typeof ImpactRoute
  JourneyRoute: typeof JourneyRoute
  ProjectsBeanhubRoute: typeof ProjectsBeanhubRoute
  ProjectsCuppingnotesRoute: typeof ProjectsCuppingnotesRoute
  ProjectsKafeyaRoute: typeof ProjectsKafeyaRoute
  ProjectsPandudesaRoute: typeof ProjectsPandudesaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/pandudesa': {
      id: '/projects/pandudesa'
      path: '/projects/pandudesa'
      fullPath: '/projects/pandudesa'
      preLoaderRoute: typeof ProjectsPandudesaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/kafeya': {
      id: '/projects/kafeya'
      path: '/projects/kafeya'
      fullPath: '/projects/kafeya'
      preLoaderRoute: typeof ProjectsKafeyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/cuppingnotes': {
      id: '/projects/cuppingnotes'
      path: '/projects/cuppingnotes'
      fullPath: '/projects/cuppingnotes'
      preLoaderRoute: typeof ProjectsCuppingnotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/beanhub': {
      id: '/projects/beanhub'
      path: '/projects/beanhub'
      fullPath: '/projects/beanhub'
      preLoaderRoute: typeof ProjectsBeanhubRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ExperienceRoute: ExperienceRoute,
  ImpactRoute: ImpactRoute,
  JourneyRoute: JourneyRoute,
  ProjectsBeanhubRoute: ProjectsBeanhubRoute,
  ProjectsCuppingnotesRoute: ProjectsCuppingnotesRoute,
  ProjectsKafeyaRoute: ProjectsKafeyaRoute,
  ProjectsPandudesaRoute: ProjectsPandudesaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
