/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsKafeyaRouteImport } from './routes/projects.kafeya'
import { Route as ProjectsBeanhubRouteImport } from './routes/projects.beanhub'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsKafeyaRoute = ProjectsKafeyaRouteImport.update({
  id: '/projects/kafeya',
  path: '/projects/kafeya',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsBeanhubRoute = ProjectsBeanhubRouteImport.update({
  id: '/projects/beanhub',
  path: '/projects/beanhub',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/projects/beanhub': typeof ProjectsBeanhubRoute
  '/projects/kafeya': typeof ProjectsKafeyaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/projects/beanhub': typeof ProjectsBeanhubRoute
  '/projects/kafeya': typeof ProjectsKafeyaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/projects/beanhub': typeof ProjectsBeanhubRoute
  '/projects/kafeya': typeof ProjectsKafeyaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/projects/beanhub' | '/projects/kafeya'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/projects/beanhub' | '/projects/kafeya'
  id: '__root__' | '/' | '/about' | '/projects/beanhub' | '/projects/kafeya'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ProjectsBeanhubRoute: typeof ProjectsBeanhubRoute
  ProjectsKafeyaRoute: typeof ProjectsKafeyaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/kafeya': {
      id: '/projects/kafeya'
      path: '/projects/kafeya'
      fullPath: '/projects/kafeya'
      preLoaderRoute: typeof ProjectsKafeyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/beanhub': {
      id: '/projects/beanhub'
      path: '/projects/beanhub'
      fullPath: '/projects/beanhub'
      preLoaderRoute: typeof ProjectsBeanhubRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ProjectsBeanhubRoute: ProjectsBeanhubRoute,
  ProjectsKafeyaRoute: ProjectsKafeyaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
